import * as O from './options'
export type FoundationInterestDeclaration=Record<string,unknown>&{phone:string;email:string;participantAge:number;activities:string[];preferredLocations:string[];availableDays:string[];alternativeLocations:string[];motivations:string[]}
type Result={ok:true;data:FoundationInterestDeclaration}|{ok:false;errors:Record<string,string>}
const s=(v:unknown,max=200)=>typeof v==='string'?v.trim().slice(0,max):''
const a=(v:unknown)=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string').map(x=>x.trim()))]:[]
const valid=(v:string,opts:readonly {value:string}[])=>O.optionValues(opts).includes(v)
export function normalizePolishPhone(v:unknown){const d=s(v,40).replace(/[^0-9+]/g,'').replace(/^0048/,'+48');const n=d.startsWith('+48')?d.slice(3):d;return /^\d{9}$/.test(n)?`+48${n}`:null}
export function validateFoundationInterest(input:unknown):Result{
 const x=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,e:Record<string,string>={};
 if(s(x.website))e.form='Nie udało się wysłać formularza.';const started=Number(x.startedAt);if(!started||Date.now()-started<2500||Date.now()-started>86400000)e.form='Odśwież stronę i spróbuj ponownie.'
 const respondentType=s(x.respondentType),participantFirstName=s(x.participantFirstName,80),participantAge=Number(x.participantAge),municipality=s(x.municipality),locality=s(x.locality,120);
 if(!valid(respondentType,O.respondentOptions))e.respondentType='Wybierz, kto wypełnia formularz.';if(!participantFirstName)e.participantFirstName='Podaj imię uczestnika.';if(!Number.isInteger(participantAge)||participantAge<9||participantAge>18)e.participantAge='Wybierz wiek od 9 do 18 lat.';if(respondentType==='adult_participant'&&participantAge!==18)e.respondentType='Pełnoletni uczestnik musi mieć 18 lat.';if(!valid(municipality,O.municipalityOptions))e.municipality='Wybierz gminę.';if(!locality)e.locality='Podaj miejscowość.'
 const activities=a(x.activities),eligible=O.activitiesForAge(participantAge).map(z=>z.value),primaryActivity=s(x.primaryActivity);if(!activities.length||activities.some(v=>!eligible.includes(v as never)))e.activities='Wybierz co najmniej jedne zajęcia zgodne z wiekiem.';if(!activities.includes(primaryActivity))e.primaryActivity='Wybierz pierwszy wybór spośród zaznaczonych zajęć.'
 const attendanceCommitment=s(x.attendanceCommitment),availableDays=a(x.availableDays),earliestStart=s(x.earliestStart);if(!valid(attendanceCommitment,O.attendanceOptions))e.attendanceCommitment='Wybierz odpowiedź.';if(!availableDays.length||availableDays.some(v=>!valid(v,O.dayOptions)))e.availableDays='Wybierz co najmniej jeden dzień.';if(!valid(earliestStart,O.earliestStartOptions))e.earliestStart='Wybierz godzinę.'
 const preferredLocations=a(x.preferredLocations),primaryLocation=s(x.primaryLocation),travelFlexibility=s(x.travelFlexibility),alternativeLocations=a(x.alternativeLocations),transportBarrier=s(x.transportBarrier);if(!preferredLocations.length||preferredLocations.some(v=>!valid(v,O.projectLocationOptions)))e.preferredLocations='Wybierz lokalizację.';if(!preferredLocations.includes(primaryLocation))e.primaryLocation='Wybierz pierwszy wybór spośród lokalizacji.';if(!valid(travelFlexibility,O.travelFlexibilityOptions))e.travelFlexibility='Wybierz odpowiedź dotyczącą dojazdu.';if(travelFlexibility==='selected_only'&&!alternativeLocations.length)e.alternativeLocations='Wybierz alternatywne lokalizacje.';if(alternativeLocations.some(v=>!valid(v,O.projectLocationOptions)))e.alternativeLocations='Wybierz poprawne lokalizacje.';if(!valid(transportBarrier,O.transportBarrierOptions))e.transportBarrier='Wybierz odpowiedź dotyczącą bariery.'
 const englishComfort=s(x.englishComfort),motivations=a(x.motivations),motivationOther=s(x.motivationOther,300)||null,organizationalNeeds=s(x.organizationalNeeds,1500)||null;if(!valid(englishComfort,O.englishComfortOptions))e.englishComfort='Wybierz odpowiedź dotyczącą angielskiego.';if(motivations.some(v=>!valid(v,O.motivationOptions)))e.motivations='Wybierz poprawne odpowiedzi.';if(motivations.includes('other')&&!motivationOther)e.motivationOther='Napisz, co jeszcze zachęca uczestnika.'
 const contactName=s(x.contactName,120),email=s(x.email,254).toLowerCase(),phone=normalizePolishPhone(x.phone),preferredContact=s(x.preferredContact);if(contactName.length<3)e.contactName='Podaj imię i nazwisko osoby kontaktowej.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))e.email='Podaj poprawny adres e-mail.';if(!phone)e.phone='Podaj polski numer telefonu.';if(!valid(preferredContact,O.preferredContactOptions))e.preferredContact='Wybierz sposób kontaktu.'
 if(x.consentDeclaration!==true)e.consentDeclaration='To potwierdzenie jest wymagane.';if(x.consentContact!==true)e.consentContact='Zgoda na kontakt jest wymagana.';if(x.privacyAcknowledged!==true)e.privacyAcknowledged='Potwierdzenie klauzuli jest wymagane.';if(Object.keys(e).length)return{ok:false,errors:e}
 return{ok:true,data:{respondentType,participantFirstName,participantAge,municipality,locality,activities,primaryActivity,attendanceCommitment,availableDays,earliestStart,preferredLocations,primaryLocation,travelFlexibility,alternativeLocations:travelFlexibility==='selected_only'?alternativeLocations:[],transportBarrier,englishComfort,motivations,motivationOther,organizationalNeeds,contactName,email,phone:phone!,preferredContact,consentDeclaration:true,consentContact:true,privacyAcknowledged:true,consentVersion:O.FOUNDATION_CONSENT_VERSION,privacyNoticeVersion:O.FOUNDATION_PRIVACY_NOTICE_VERSION}}
}
