/* eslint-disable @typescript-eslint/no-explicit-any */
'use client'
import Link from 'next/link';import {FormEvent,useEffect,useRef,useState} from 'react';import Button from '../Button';import * as O from '@/lib/foundation/options';import {validateFoundationInterest} from '@/lib/foundation/validation';import styles from './FoundationInterestForm.module.css'
type Props={copy:any;locale:string};type Errors=Record<string,string>
const Choice=({name,options,type='radio',disabled}:{name:string;options:readonly {value:string;label:string}[];type?:string;disabled?:(v:string)=>boolean})=><div className={styles.choices}>{options.map(o=><label key={o.value} className={disabled?.(o.value)?styles.disabled:''}><input type={type} name={name} value={o.value} disabled={disabled?.(o.value)}/><span>{o.label}</span></label>)}</div>
const Err=({n,e}:{n:string;e:Errors})=>e[n]?<p className={styles.error}>{e[n]}</p>:null
export default function FoundationInterestForm({copy,locale}:Props){
 const started=useRef(0),summary=useRef<HTMLDivElement>(null);const[age,setAge]=useState(''),[acts,setActs]=useState<string[]>([]),[locs,setLocs]=useState<string[]>([]),[travel,setTravel]=useState(''),[motivations,setMotivations]=useState<string[]>([]),[errors,setErrors]=useState<Errors>({}),[sending,setSending]=useState(false),[done,setDone]=useState(false);useEffect(()=>{started.current=Date.now()},[])
 const readChecks=(f:FormData,n:string)=>f.getAll(n).map(String)
 async function submit(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const form=ev.currentTarget,f=new FormData(form),payload={respondentType:f.get('respondentType'),participantFirstName:f.get('participantFirstName'),participantAge:f.get('participantAge'),municipality:f.get('municipality'),locality:f.get('locality'),activities:readChecks(f,'activities'),primaryActivity:f.get('primaryActivity'),attendanceCommitment:f.get('attendanceCommitment'),availableDays:readChecks(f,'availableDays'),earliestStart:f.get('earliestStart'),preferredLocations:readChecks(f,'preferredLocations'),primaryLocation:f.get('primaryLocation'),travelFlexibility:f.get('travelFlexibility'),alternativeLocations:readChecks(f,'alternativeLocations'),transportBarrier:f.get('transportBarrier'),englishComfort:f.get('englishComfort'),motivations:readChecks(f,'motivations'),motivationOther:f.get('motivationOther'),organizationalNeeds:f.get('organizationalNeeds'),contactName:f.get('contactName'),email:f.get('email'),phone:f.get('phone'),preferredContact:f.get('preferredContact'),consentDeclaration:f.get('consentDeclaration')==='on',consentContact:f.get('consentContact')==='on',privacyAcknowledged:f.get('privacyAcknowledged')==='on',website:f.get('website'),startedAt:started.current};const v=validateFoundationInterest(payload);if(!v.ok){setErrors(v.errors);requestAnimationFrame(()=>summary.current?.focus());return}setSending(true);setErrors({});try{const r=await fetch('/api/foundation-interest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json().catch(()=>({}));if(!r.ok){setErrors(j.errors||{form:j.error||copy.genericError});requestAnimationFrame(()=>summary.current?.focus())}else setDone(true)}catch{setErrors({form:copy.genericError})}finally{setSending(false)}}
 if(done)return <div className={`${styles.shell} ${styles.success}`} role="status"><h3>{copy.successTitle}</h3><p>{copy.successText}</p></div>
 return <form className={styles.shell} onSubmit={submit} noValidate><p>{copy.requiredHint}</p>{Object.keys(errors).length>0&&<div ref={summary} tabIndex={-1} role="alert" className={styles.summary}><h3>{copy.errorTitle}</h3><ul>{Object.values(errors).map(x=><li key={x}>{x}</li>)}</ul></div>}<div className={styles.honey}><input name="website" tabIndex={-1} autoComplete="off"/></div>
 <fieldset><legend>{copy.sections.participant}</legend><label className={styles.label}>Kto wypełnia formularz? *</label><Choice name="respondentType" options={O.respondentOptions}/><Err n="respondentType" e={errors}/><div className={styles.cols}><label>Imię uczestnika *<input name="participantFirstName" maxLength={80}/><small>Bez nazwiska niepełnoletniego uczestnika.</small><Err n="participantFirstName" e={errors}/></label><label>Wiek uczestnika *<select name="participantAge" value={age} onChange={e=>{const a=e.target.value;setAge(a);setActs(v=>v.filter(id=>O.activitiesForAge(Number(a)).some(x=>x.value===id)))}}><option value="">Wybierz</option>{Array.from({length:10},(_,i)=>i+9).map(x=><option key={x}>{x}</option>)}</select><Err n="participantAge" e={errors}/></label></div><div className={styles.cols}><label>Gmina zamieszkania *<select name="municipality"><option value="">Wybierz</option>{O.municipalityOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><Err n="municipality" e={errors}/></label><label>Miejscowość zamieszkania *<input name="locality" maxLength={120}/><small>Nie podawaj adresu, daty urodzenia ani PESEL.</small><Err n="locality" e={errors}/></label></div></fieldset>
 <fieldset><legend>{copy.sections.preferences}</legend><label className={styles.label}>Którymi zajęciami jest zainteresowany uczestnik? *</label><div className={styles.choices}>{O.activityOptions.map(x=>{const disabled=!age||Number(age)<x.minAge||Number(age)>x.maxAge;return <label key={x.value} className={disabled?styles.disabled:''}><input type="checkbox" name="activities" value={x.value} disabled={disabled} checked={acts.includes(x.value)} onChange={e=>setActs(v=>e.target.checked?[...v,x.value]:v.filter(y=>y!==x.value))}/><span>{x.label}</span></label>})}</div><Err n="activities" e={errors}/><label>Pierwszy wybór *<select name="primaryActivity"><option value="">Wybierz</option>{O.activityOptions.filter(x=>acts.includes(x.value)).map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><Err n="primaryActivity" e={errors}/></label><label className={styles.label}>Gotowość do regularnego udziału 15.10.2026–15.04.2027 *</label><Choice name="attendanceCommitment" options={O.attendanceOptions}/><Err n="attendanceCommitment" e={errors}/><label className={styles.label}>Dostępne dni *</label><Choice name="availableDays" options={O.dayOptions} type="checkbox"/><Err n="availableDays" e={errors}/><label>Najwcześniejsza godzina *<select name="earliestStart"><option value="">Wybierz</option>{O.earliestStartOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><Err n="earliestStart" e={errors}/></label></fieldset>
 <fieldset><legend>{copy.sections.location}</legend><label className={styles.label}>Preferowane lokalizacje *</label><div className={styles.choices}>{O.projectLocationOptions.map(x=><label key={x.value}><input type="checkbox" name="preferredLocations" value={x.value} checked={locs.includes(x.value)} onChange={e=>setLocs(v=>e.target.checked?[...v,x.value]:v.filter(y=>y!==x.value))}/><span>{x.label}</span></label>)}</div><Err n="preferredLocations" e={errors}/><label>Pierwszy wybór lokalizacji *<select name="primaryLocation"><option value="">Wybierz</option>{O.projectLocationOptions.filter(x=>locs.includes(x.value)).map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><Err n="primaryLocation" e={errors}/></label><label className={styles.label}>Możliwość dojazdu do innej lokalizacji *</label><div onChange={(e:any)=>setTravel(e.target.value)}><Choice name="travelFlexibility" options={O.travelFlexibilityOptions}/></div><Err n="travelFlexibility" e={errors}/>{travel==='selected_only'&&<><label className={styles.label}>Możliwe lokalizacje alternatywne *</label><Choice name="alternativeLocations" options={O.projectLocationOptions} type="checkbox"/><Err n="alternativeLocations" e={errors}/></>}<label className={styles.label}>Czy dojazd może stanowić barierę? *</label><Choice name="transportBarrier" options={O.transportBarrierOptions}/><Err n="transportBarrier" e={errors}/></fieldset>
 <fieldset><legend>{copy.sections.language}</legend><label className={styles.label}>Jak uczestnik czuje się podczas komunikacji po angielsku? *</label><small>{copy.englishHint}</small><Choice name="englishComfort" options={O.englishComfortOptions}/><Err n="englishComfort" e={errors}/><label className={styles.label}>Co najbardziej zachęca uczestnika?</label><div onChange={(e:any)=>{if(e.target.name==='motivations')setMotivations(v=>e.target.checked?[...v,e.target.value]:v.filter(x=>x!==e.target.value))}}><Choice name="motivations" options={O.motivationOptions} type="checkbox"/></div>{motivations.includes('other')&&<label>Inne<input name="motivationOther" maxLength={300}/></label>}<label>Co organizacyjnie ułatwiłoby regularny udział?<textarea name="organizationalNeeds" maxLength={1500} rows={5}/><small>{copy.organizationHint}</small></label></fieldset>
 <fieldset><legend>{copy.sections.contact}</legend><label>Imię i nazwisko rodzica, opiekuna albo pełnoletniego uczestnika *<input name="contactName" autoComplete="name"/><Err n="contactName" e={errors}/></label><div className={styles.cols}><label>Adres e-mail *<input name="email" type="email" autoComplete="email"/><Err n="email" e={errors}/></label><label>Numer telefonu *<input name="phone" type="tel" autoComplete="tel" placeholder="666 661 750 lub +48…"/><Err n="phone" e={errors}/></label></div><label className={styles.label}>Preferowany sposób kontaktu *</label><Choice name="preferredContact" options={O.preferredContactOptions}/><Err n="preferredContact" e={errors}/></fieldset>
 <fieldset><legend>{copy.sections.consents}</legend>{['consentDeclaration','consentContact','privacyAcknowledged'].map((n,i)=><div key={n}><label className={styles.consent}><input type="checkbox" name={n}/><span>{copy.consents[i]} {i===2&&<Link href={`/${locale}/foundation/privacy`} target="_blank">{copy.privacyLink}</Link>} *</span></label><Err n={n} e={errors}/></div>)}</fieldset><Button href={null} type="submit" fullWidth disabled={sending}>{sending?copy.submitting:copy.submit}</Button></form>
}
