create table public.foundation_interest_declarations (
 id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),status text not null default 'new' check(status in('new','contacted','archived')),
 respondent_type text not null check(respondent_type in('parent_guardian','adult_participant','young_with_guardian')),participant_first_name text not null check(char_length(participant_first_name) between 1 and 80),participant_age smallint not null check(participant_age between 9 and 18),municipality text not null check(municipality in('tarnowo_podgorne','kazmierz','rokietnica','szamotuly','other')),locality text not null,
 activities text[] not null check(cardinality(activities)>0),primary_activity text not null,attendance_commitment text not null,available_days text[] not null check(cardinality(available_days)>0),earliest_start text not null,
 preferred_locations text[] not null check(cardinality(preferred_locations)>0),primary_location text not null,travel_flexibility text not null,alternative_locations text[] not null default '{}',transport_barrier text not null,english_comfort text not null,motivations text[] not null default '{}',motivation_other text,organizational_needs text,
 contact_name text not null,email text not null,phone text not null check(phone~'^\+48[0-9]{9}$'),preferred_contact text not null,
 consent_declaration boolean not null check(consent_declaration),consent_contact boolean not null check(consent_contact),privacy_acknowledged boolean not null check(privacy_acknowledged),consent_version text not null,privacy_notice_version text not null,consented_at timestamptz not null default now(),
 check(respondent_type<>'adult_participant' or participant_age=18),check(primary_activity=any(activities)),check(primary_location=any(preferred_locations)),check(travel_flexibility<>'selected_only' or cardinality(alternative_locations)>0),
 check(activities<@array['teenpreneurs','creative_diy','podcasts_audio_video','art_performance_9_13','art_performance_13_18']::text[]),check(available_days<@array['monday','tuesday','wednesday','thursday','friday','saturday']::text[]),check(preferred_locations<@array['tarnowo_podgorne','kazmierz','rokietnica','szamotuly']::text[] and alternative_locations<@array['tarnowo_podgorne','kazmierz','rokietnica','szamotuly']::text[])
);
comment on table public.foundation_interest_declarations is 'Badanie zainteresowania projektem Kreatorzy Przyszłości — nie jest formalnym zapisem ani leadem sprzedażowym.';
create index foundation_interest_created_at_idx on public.foundation_interest_declarations(created_at desc);create index foundation_interest_status_idx on public.foundation_interest_declarations(status,created_at desc);
create trigger foundation_interest_set_updated_at before update on public.foundation_interest_declarations for each row execute procedure public.set_updated_at();
alter table public.foundation_interest_declarations enable row level security;revoke all on table public.foundation_interest_declarations from public,anon,authenticated;grant select,update on table public.foundation_interest_declarations to authenticated;grant all on table public.foundation_interest_declarations to service_role;
create policy "Tylko admin odczytuje deklaracje Fundacji" on public.foundation_interest_declarations for select to authenticated using(public.current_user_role()='admin'::public.user_role);
create policy "Tylko admin aktualizuje deklaracje Fundacji" on public.foundation_interest_declarations for update to authenticated using(public.current_user_role()='admin'::public.user_role) with check(public.current_user_role()='admin'::public.user_role);
